version: "3.4"

services:
  dev_go:
    container_name: request_record_middleware_dev
    working_dir: /work
    image: golang:1.21.4-bullseye
    tty: true
    volumes:
      - type: bind
        source: .
        target: /work
    profiles:
      - dev
  dev_front:
    container_name: request_record_middleware_dev_front
    working_dir: /work
    image: node:20.10-bullseye
    tty: true
    volumes:
      - type: bind
        source: .
        target: /work
    profiles:
      - dev
