version: "3.4"

services:
  dev:
    container_name: request_record_middleware_dev
    working_dir: /work
    image: golang:1.21.4-bullseye
    tty: true
    volumes:
      - type: bind
        source: .
        target: /work
    profiles:
      - dev
